Reorganzing action pyproject-install-pip-modules

diff --git a/.github/actions/pyproject-install-pip-modules/action.yml b/.github/actions/pyproject-install-pip-modules/action.yml
--- a/.github/actions/pyproject-install-pip-modules/action.yml
+++ b/.github/actions/pyproject-install-pip-modules/action.yml
@@ -88,18 +88,60 @@ runs:
         pip install flit
         echo "::endgroup::"
         echo "Installing all necessary packages with flit ..."
-        if [[ "${INSTALL_PYTEST}" == false ]] ; then
+        if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
+            echo "Installation of Linter tools not necessary."
+        else
             echo "Installing linting modules ..."
             echo "::group::Flit install lint"
             flit install --only-deps --deps production --extras lint --python .venv/bin/python3
             echo "::endgroup::"
         fi
-        if [[ "${INSTALL_LINTER_TOOLS}" == false ]] ; then
-            echo "Installing test modules ..."
-            echo "::group::Flit install testing"
-            flit install --only-deps --deps production --extras testing --python .venv/bin/python3
+
+    - name: Install linter tools
+      id: install-linter
+      if: ${{ inputs.install_linter_tools }}
+      env:
+        FLIT_ROOT_INSTALL: 1
+      shell: bash
+      run: |
+        echo "Installing shellcheck and yamllint ..."
+        if type -p apt >/dev/null; then
+            echo "::group::Executing: apt install --yes shellcheck yamllint"
+            apt install --yes shellcheck yamllint
             echo "::endgroup::"
+        elif type -p dnf >/dev/null; then
+            echo "::group::Executing: dnf --assumeyes install ShellCheck yamllint"
+            dnf --assumeyes install ShellCheck yamllint
+            echo "::endgroup::"
+        elif type -p yum >/dev/null; then
+            echo "::group::Executing: yum --assumeyes install ShellCheck yamllint"
+            yum --assumeyes install ShellCheck yamllint
+            echo "::endgroup::"
+        else
+            echo "::error::Did not found apt, dnf or yum."
+            exit 5
         fi
+        echo "Activating virtual environment '.venv'."
+        source .venv/bin/activate
+        echo "Installing linting modules with flit ..."
+        echo "::group::Flit install lint"
+        flit install --only-deps --deps production --extras lint --python .venv/bin/python3
+        echo "::endgroup::"
+
+    - name: Install Pytest
+      id: install-pytest
+      if: ${{ inputs.install_pytest }}
+      env:
+        FLIT_ROOT_INSTALL: 1
+      id: inst-pytest
+      shell: bash
+      run: |
+        echo "Activating virtual environment '.venv'."
+        source .venv/bin/activate
+        echo "Installing test modules with flit ..."
+        echo "::group::Flit install testing"
+        flit install --only-deps --deps production --extras testing --python .venv/bin/python3
+        echo "::endgroup::"
 
     - name: Show installed Python modules
       id: show-py-modules
