Changing logging output

diff --git a/.github/workflows/build-python-debian-packages.yaml b/.github/workflows/build-python-debian-packages.yaml
--- a/.github/workflows/build-python-debian-packages.yaml
+++ b/.github/workflows/build-python-debian-packages.yaml
@@ -57,14 +57,14 @@ jobs:
         id: apt-update
         shell: bash
         run: |
-          echo "::notice::Update all package lists."
+          echo "Update all package lists."
           apt update --yes
 
       - name: "Install JQ"
         shell: bash
         run: |
           apt install --yes jq
-          echo "::notice::Version of JQ: $( jq --version )"
+          echo -e "\nVersion of JQ: $( jq --version )"
 
       - name: "Defining the build-matrix"
         id: set-matrix
@@ -92,7 +92,7 @@ jobs:
                 matrix_json+="\"version_prefix\": \"deb11\", "
                 matrix_json+="\"compat\": \"12\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Debian 11 Bullseye"
+                echo "::notice title=Define Debian build matrix::Adding Debian 11 Bullseye"
                 ;;
               debian-bookworm)
                 if [[ "${matrix_json}" != '[' ]] ; then
@@ -107,7 +107,7 @@ jobs:
                 matrix_json+="\"version_prefix\": \"deb12\", "
                 matrix_json+="\"compat\": \"12\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Debian 12 Bookworm"
+                echo "::notice title=Define Debian build matrix::Adding Debian 12 Bookworm"
                 ;;
               debian-trixie)
                 if [[ "${matrix_json}" != '[' ]] ; then
@@ -122,7 +122,7 @@ jobs:
                 matrix_json+="\"version_prefix\": \"deb13\", "
                 matrix_json+="\"compat\": \"13\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Debian 13 Trixie"
+                echo "::notice title=Define Debian build matrix::Adding Debian 13 Trixie"
                 ;;
               ubuntu-focal)
                 if [[ "${matrix_json}" != '[' ]] ; then
@@ -137,7 +137,7 @@ jobs:
                 matrix_json+="\"version_prefix\": \"ubuntu20.04\", "
                 matrix_json+="\"compat\": \"12\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Ubuntu 20.04 Focal Fossa"
+                echo "::notice title=Define Debian build matrix::Adding Ubuntu 20.04 Focal Fossa"
                 ;;
               ubuntu-jammy)
                 if [[ "${matrix_json}" != '[' ]] ; then
@@ -152,7 +152,7 @@ jobs:
                 matrix_json+="\"version_prefix\": \"ubuntu22.04\", "
                 matrix_json+="\"compat\": \"12\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Ubuntu 22.04 Jammy Jellyfish"
+                echo "::notice title=Define Debian build matrix::Adding Ubuntu 22.04 Jammy Jellyfish"
                 ;;
               ubuntu-noble)
                 if [[ "${matrix_json}" != '[' ]] ; then
@@ -167,10 +167,10 @@ jobs:
                 matrix_json+="\"version_prefix\": \"ubuntu24.04\", "
                 matrix_json+="\"compat\": \"12\""
                 matrix_json+="}"
-                echo "::notice file=build-python-debian-packages.yaml,title=Define build matrix::Adding Ubuntu 24.04 Noble Numbat"
+                echo "::notice title=Define Debian build matrix::Adding Ubuntu 24.04 Noble Numbat"
                 ;;
               *)
-                echo "::error file=build-python-debian-packages.yaml,title=Define build matrix::Unknown Debian or Ubuntu version '${deb_version}' given." >&2
+                echo "::error title=Define Debian build matrix::Unknown Debian or Ubuntu version '${deb_version}' given." >&2
                 exit 6
                 ;;
             esac
@@ -193,15 +193,16 @@ jobs:
     steps:
       - name: "Checking out sources."
         uses: actions/checkout@v4
+
       - name: "Show Environment"
         shell: bash
         run: |
           if [[ -f /etc/os-release ]] ; then
-            echo "::notice::OS release:"
+            echo "OS release for building source package:"
             cat /etc/os-release
           fi
-          echo "::notice::Bash enviroment:"
-          env | sort
+          echo -e "\nBash enviroment:"
+          env
 
   ###########################
   build_debian_bin:
@@ -209,21 +210,22 @@ jobs:
     needs:
       - define-debian-build-matrix
     name: Building Debian Binary Packages for ${{ matrix.title }}
-    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/test') || startsWith(github.ref, 'refs/tags/') }}
+    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' || startsWith(github.ref_name, 'test') || github.ref_name == 'dev/workflow' || startsWith(github.ref, 'refs/tags/')  }}
     strategy:
       fail-fast: false
       matrix: ${{ fromJSON(needs.define-debian-build-matrix.outputs.matrix) }}
     steps:
       - name: "Checking out sources."
         uses: actions/checkout@v4
+
       - name: "Show Environment"
         shell: bash
         run: |
           if [[ -f /etc/os-release ]] ; then
-            echo "::notice::OS release:"
+            echo "OS release:"
             cat /etc/os-release
           fi
-          echo "::notice::Bash enviroment:"
+          echo -e "\nBash enviroment:"
           env | sort
 
 # vim: et tabstop=2 expandtab shiftwidth=2 softtabstop=2 list
diff --git a/.github/workflows/python-linter-tests.yaml b/.github/workflows/python-linter-tests.yaml
--- a/.github/workflows/python-linter-tests.yaml
+++ b/.github/workflows/python-linter-tests.yaml
@@ -42,25 +42,33 @@ jobs:
     steps:
       - name: "Checking out the sources."
         uses: actions/checkout@v4
+
       - name: "Preparing the Debian container"
         uses: fbrehm/prepare-debian-container@main
+
       - name: "Installing necessary PIP modules and linter tools."
         uses: fbrehm/github-install-pip-modules@main
         with:
           install_linter_tools: true
+
+      - name: "Show Environment"
+        shell: bash
+        run: |
+          echo "Bash enviroment:"
+          env
 
       - name: Checking validity of libdir ${[ inputs.libdir }}.
         shell: bash
         run: |
           echo -e -n "\nChecking for directory '${LIBDIR}': "
           if [[ ! -d "${LIBDIR}" ]] ; then
-            echo "Python libdir '${LIBDIR}' does not exists." >&2
+            echo "::error::Python libdir '${LIBDIR}' does not exists." >&2
             exit 6
           fi
           echo "ok."
           echo -e -n "\nChecking for file '${INDEX_FILE}': "
           if [[ ! -f "${INDEX_FILE}" ]] ; then
-            echo "Python package index file '${INDEX_FILE}' does not exists." >&2
+            echo "::error::Python package index file '${INDEX_FILE}' does not exists." >&2
             exit 6
           fi
           echo "ok."
@@ -68,35 +76,36 @@ jobs:
       - name: "Checking module version against tag."
         shell: bash
         run: |
-          MODULE_VERSION=$( cat "${INDEX_FILE}" | grep -P '^__version__(\s|=)' | sed -e "s/^[^'\"]*['\"]//"  -e "s/['\"][ »]*\$//" )
-          echo "Module version: '${MODULE_VERSION}'"
-          if echo "${GITREF}" | grep -q -P '^refs/tags/' ; then
-              TAG_VERSION=$( echo "${GITREF}" | sed -e 's|^refs/tags/||' )
-              if [[ "${MODULE_VERSION}" == "${TAG_VERSION}" ]] ; then
-                  echo "Tag and module version '${TAG_VERSION}' are okay."
-              else
-                  echo "Tag '${TAG_VERSION}' does not match module version '${MODULE_VERSION}'" >&2
-                  exit 5
-              fi
+          PACKAGE_VERSION=$( cat "${INDEX_FILE}" | grep -P '^__version__(\s|=)' | sed -e "s/^[^'\"]*['\"]//"  -e "s/['\"][ »]*\$//" )
+          echo "::notice::Package version: '${PACKAGE_VERSION}'"
+          #if echo "${GITREF}" | grep -q -P '^refs/tags/' ; then
+          if [[ "${GITHUB_REF_TYPE}" == 'tag' ]] ; then
+            # TAG_VERSION=$( echo "${GITREF}" | sed -e 's|^refs/tags/||' )
+            if [[ "${PACKAGE_VERSION}" == "${GITHUB_REF_NAME}" ]] ; then
+            echo "Tag and package version '${GITHUB_REF_NAME}' are okay."
+            else
+              echo "::error::Tag '${GITHUB_REF_NAME}' does not match package version '${PACKAGE_VERSION}'" >&2
+              exit 5
+            fi
           fi
 
-      - name: "Comparing package version in debian/changlog and in lib/fb_vmware/__init__.py."
+      - name: Comparing package version in debian/changlog and in ${{ inputs.libdir }}/__init__.py.
         shell: bash
         run: |
           echo "Getting package version from '${INDEX_FILE}' ..."
-          MODULE_VERSION=$( cat "${INDEX_FILE}" | grep -P '^__version__(\s|=)' | sed -e "s/^[^'\"]*['\"]//"  -e "s/['\"][ 	]*\$//" )
-          echo "Module version: '${MODULE_VERSION}'"
+          PACKAGE_VERSION=$( cat "${INDEX_FILE}" | grep -P '^__version__(\s|=)' | sed -e "s/^[^'\"]*['\"]//"  -e "s/['\"][ 	]*\$//" )
+          echo "Package version: '${PACKAGE_VERSION}'"
           if [[ -f debian/changelog ]] ; then
             DEBIAN_PKG_VERSION=$( head -n 1 debian/changelog | sed -e 's/^[^(]*(//' -e 's/).*//' )
             echo "Debian package version: '${DEBIAN_PKG_VERSION}'"
-            if [[ "${MODULE_VERSION}" == "${DEBIAN_PKG_VERSION}" ]] ; then
-                echo "Debian package version and package version '${DEBIAN_PKG_VERSION}' are matching."
+            if [[ "${PACKAGE_VERSION}" == "${DEBIAN_PKG_VERSION}" ]] ; then
+              echo "Debian package version and package version '${DEBIAN_PKG_VERSION}' are matching."
             else
-                echo "Debian package version '${DEBIAN_PKG_VERSION}' does not match package version '${MODULE_VERSION}'" >&2
-                exit 5
+              echo "::error::Debian package version '${DEBIAN_PKG_VERSION}' does not match package version '${PACKAGE_VERSION}'" >&2
+              exit 5
             fi
           else
-            echo "File 'debian/changelog' not found." >&2
+            echo "::error::File 'debian/changelog' not found." >&2
             exit 7
           fi
 
@@ -142,7 +151,7 @@ jobs:
           echo -n "Version of shellcheck: "
           shellcheck --version
           echo -e "\nChecking with shellcheck: ${shellscripts} ..."
-          echo -e "shellcheck -x ${shellscripts}"
+          echo "::debug::shellcheck -x ${shellscripts}"
           shellcheck -x ${shellscripts}
 
       - name: Execute Yamllint
