Trying to fix .github/workflows/pyproject-build-rpm-pkgs.yaml and .github/workflows/pyproject-build-debian-pkgs.yaml

diff --git a/.github/workflows/pyproject-build-debian-pkgs.yaml b/.github/workflows/pyproject-build-debian-pkgs.yaml
--- a/.github/workflows/pyproject-build-debian-pkgs.yaml
+++ b/.github/workflows/pyproject-build-debian-pkgs.yaml
@@ -498,39 +498,40 @@ jobs:
         run: |
             echo '.'
             echo "KEEP_TOMLI: '${KEEP_TOMLI}'"
-            echo '.'
-            echo "Checking Python version ..."
-            python3 --version
-            # if python3 --version | grep -P -q '\s3\.(1[1-9]|[2-9]\d)' && "${KEEP_TOMLI}" == false ; then
-            if python3 --version | grep -P -q '\s3\.(1[1-9]|[2-9]\d)'; then
-                echo "Checking for tomli in pyproject.toml ..."
-                if grep -q -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
-                    echo '.'
-                    echo "Removing all occurences of 'tomli' from pyproject.toml ..."
-                    sed -i -e 's/[ 	][ 	]*tomli[, 	]/ /g' -e 's/[ 	]*"tomli"[, 	]/ /g' -e "s/[ 	]*'tomli'[, 	]/ /g" pyproject.toml
-                    sed -i -e '/^[ 	][ 	]*$/d' pyproject.toml
-                    echo '.'
-                    echo "::group::Mangled pyproject.toml"
-                    cat pyproject.toml
-                    echo "::endgroup::"
-                    if grep -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
-                        echo "Could not remove 'tomli' completely from pyproject.toml." >&2
-                        exit 5
+            if [[ "${KEEP_TOMLI}" == false ]] ; then
+                echo '.'
+                echo "Checking Python version ..."
+                python3 --version
+                if python3 --version | grep -P -q '\s3\.(1[1-9]|[2-9]\d)'; then
+                    echo "Checking for tomli in pyproject.toml ..."
+                    if grep -q -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
+                        echo '.'
+                        echo "Removing all occurences of 'tomli' from pyproject.toml ..."
+                        sed -i -e 's/[ 	][ 	]*tomli[, 	]/ /g' -e 's/[ 	]*"tomli"[, 	]/ /g' -e "s/[ 	]*'tomli'[, 	]/ /g" pyproject.toml
+                        sed -i -e '/^[ 	][ 	]*$/d' pyproject.toml
+                        echo '.'
+                        echo "::group::Mangled pyproject.toml"
+                        cat pyproject.toml
+                        echo "::endgroup::"
+                        if grep -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
+                            echo "Could not remove 'tomli' completely from pyproject.toml." >&2
+                            exit 5
+                        fi
                     fi
-                fi
-                echo "Checking for tomli in debian/control ..."
-                if grep -q -w -P 'python3-tomli[^-_a-z0-9]' debian/control ; then
-                    echo '.'
-                    echo "Removing all occurences of 'tomli' debian/control ..."
-                    sed -i -e 's/ python3-tomli,//g' debian/control
-                    sed -i -e '/^[ 	][ 	]*$/d' debian/control
-                    echo '.'
-                    echo "::group::Mangled debian/control"
-                    cat debian/control
-                    echo "::endgroup::"
-                    if grep -w -P 'python3-tomli[^-_a-z0-9]' debian/control ; then
-                        echo "Could not remove 'python3-tomli' completely from debian/control." >&2
-                        exit 5
+                    echo "Checking for tomli in debian/control ..."
+                    if grep -q -w -P 'python3-tomli[^-_a-z0-9]' debian/control ; then
+                        echo '.'
+                        echo "Removing all occurences of 'tomli' debian/control ..."
+                        sed -i -e 's/ python3-tomli,//g' debian/control
+                        sed -i -e '/^[ 	][ 	]*$/d' debian/control
+                        echo '.'
+                        echo "::group::Mangled debian/control"
+                        cat debian/control
+                        echo "::endgroup::"
+                        if grep -w -P 'python3-tomli[^-_a-z0-9]' debian/control ; then
+                            echo "Could not remove 'python3-tomli' completely from debian/control." >&2
+                            exit 5
+                        fi
                     fi
                 fi
             fi
