Disable RPM dependencies for python3-tomli on higher Python versions

diff --git a/.github/workflows/pyproject-build-rpm-pkgs.yaml b/.github/workflows/pyproject-build-rpm-pkgs.yaml
--- a/.github/workflows/pyproject-build-rpm-pkgs.yaml
+++ b/.github/workflows/pyproject-build-rpm-pkgs.yaml
@@ -85,6 +85,10 @@ on:
         description: "The data directory for containing man pages, i18n files a.s.o."
         type: string
         default: ''
+      keep_tomli:
+        description: "Keeping dependencies to Python tomli, even it is Python version >= 3.11."
+        type: boolean
+        default: false
       revision:
         description: "Revision count for current version."
         type: string
@@ -447,6 +451,51 @@ jobs:
           echo '.'
           echo "File /usr/share/zoneinfo/zone.tab:"
           ls -l --color=always /usr/share/zoneinfo/zone.tab
+
+      - name: "Remove python package tomli as a dependency"
+        env:
+          KEEP_TOMLI: ${{ inputs.keep_tomli }}
+        id: remove-tomli-dependency
+        shell: bash
+        run: |
+            echo '.'
+            echo "KEEP_TOMLI: '${KEEP_TOMLI}'"
+            echo '.'
+            echo "Checking Python version ..."
+            python3 --version
+            # if python3 --version | grep -P -q '\s3\.(1[1-9]|[2-9]\d)' && "${KEEP_TOMLI}" == false ; then
+            if python3 --version | grep -P -q '\s3\.(1[1-9]|[2-9]\d)'; then
+                echo "Checking for tomli in pyproject.toml ..."
+                if grep -q -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
+                    echo '.'
+                    echo "Removing all occurences of 'tomli' from pyproject.toml ..."
+                    sed -i -e 's/[ 	][ 	]*tomli[, 	]/ /g' -e 's/[ 	]*"tomli"[, 	]/ /g' -e "s/[ 	]*'tomli'[, 	]/ /g" pyproject.toml
+                    sed -i -e '/^[ 	][ 	]*$/d' pyproject.toml
+                    echo '.'
+                    echo "::group::Mangled pyproject.toml"
+                    cat pyproject.toml
+                    echo "::endgroup::"
+                    if grep -w -P 'tomli[^-_a-z0-9]' pyproject.toml ; then
+                        echo "Could not remove 'tomli' completely from pyproject.toml." >&2
+                        exit 5
+                    fi
+                fi
+                template="${{ inputs.template_specfile }}"
+                echo "Checking for tomli in ${template} ..."
+                if grep -q -w -P 'python.*-tomli[^-_a-z0-9]' ${template} ; then
+                    echo '.'
+                    echo "Removing all occurences of 'tomli' in ${template} ..."
+                    sed -i -e '/python.*-tomli[^-_a-z0-9]/d' ${template}
+                    echo '.'
+                    echo "::group::Mangled ${template}"
+                    cat ${template}
+                    echo "::endgroup::"
+                    if grep -w -P 'python.*-tomli[^-_a-z0-9]' ${template} ; then
+                        echo "Could not remove 'python3-tomli' completely from ${template}." >&2
+                        exit 5
+                    fi
+                fi
+            fi
 
       - name: 'Install Python 3'
         id: install-python3
